apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: hello-arc
  chart:
    spec:
      chart: ./hello-arc/charts/hello-arc
  values:
    image:
      repository: azurearcjumpstart.azurecr.io/hello-arc-gitops
      tag: latest
    replicaCount: 3
    env:
      name: MESSAGE
      value: ¡Bienvenid@s a la Demo de Azure Arc GitOps 28/Sep/2022 !!!
